# https://school.programmers.co.kr/learn/courses/30/lessons/301651
# Write your MySQL query statement below

WITH RECURSIVE GEN_DATA AS (
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, G.GENERATION + 1
    FROM GEN_DATA G
    JOIN ECOLI_DATA E ON G.ID = E.PARENT_ID
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM GEN_DATA
WHERE ID NOT IN (SELECT PARENT_ID FROM ECOLI_DATA WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION
ORDER BY GENERATION
